name: vorpal-sandbox

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - if: matrix.runner != 'macos-latest'
        run: ./script/debian.sh "sandbox"

      - run: make dist

      - run: |
          echo "ARCH=$(uname -m | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "OS=$(uname -s | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "SANDBOX_HASH=$(cat "${PWD}/script/sandbox.sha256sum")" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: vorpal-sandbox-${{ env.ARCH }}-${{ env.OS }}
          path: dist/vorpal-sandbox-${{ env.SANDBOX_HASH }}.package.tar.zst
